### ISSUE TITLE
Comparing objects length instead of content

### ISSUE THREAD

**Issue by YahyaAlfayad** [mahmoudaboc/java-script#11]
https://github.com/mahmoudaboc/java-script/blob/7c00350e35f9c5238e1d2a20fd929a5468170325/HomeWork-week2/home%20work%20js%20week%202.js#L120

This compares object length instead of the content. You need to iterate over the object keys and values and compare them one by one.

**Comment by mahmoudaboc** [comment]
I correct it , I hope it it okay , Thanks you
