### ISSUE TITLE
Change the property values besides assign the object to new variable only

### ISSUE THREAD

**Issue by YahyaAlfayad** [mahmoudaboc/java-script#13]
https://github.com/mahmoudaboc/java-script/blob/7c00350e35f9c5238e1d2a20fd929a5468170325/HomeWork-week2/home%20work%20js%20week%202.js#L163

The idea of changing is to change the properties of the objects not just assigning the object's variable to new value. For example try to change `o1.foo` no a new value.

**Comment by mahmoudaboc** [comment]
I did it , Thank you 👍
