### ISSUE TITLE
repository structure and naming

### ISSUE THREAD

**Issue by mkruijt** [mahmoudaboc/java-script#16]
Hi Mahmoud, can you please improve the structure of your repositories?

You are almost there, only watch out for capital letters and spaces in names, can you please get all of those out? For example you have a, "Week 1", "Week 2", "Week3" and "week4".

be consistent in what you do, I would suggest the following:
(also week4 should be in a new repository, it's week1 of javascript2)

You should have a repository for every module eg:
hyf-html-css
hyf-javascript1
hyf-javascript2

inside you should have all weeks in folders, so:
hyf-javascript1/week1/
hyf-javascript1/week2/
hyf-javascript1/week3/

inside these week you place your homework assignments.

if this is not clear please take a look at the example 1 made:
https://github.com/mkruijt/HTML-CSS

**Comment by mahmoudaboc** [comment]
Hi , yes , I did it 
Thank you
